export const BANK_RATES = [
  { id: 'sbi', name: 'State Bank of India (SBI)', rate: 8.50 },
  { id: 'hdfc', name: 'HDFC Bank', rate: 8.75 },
  { id: 'icici', name: 'ICICI Bank', rate: 8.75 },
  { id: 'axis', name: 'Axis Bank', rate: 8.75 },
  { id: 'kotak', name: 'Kotak Mahindra Bank', rate: 8.75 },
  { id: 'pnb', name: 'Punjab National Bank (PNB)', rate: 8.45 },
  { id: 'bob', name: 'Bank of Baroda', rate: 8.40 },
  { id: 'union', name: 'Union Bank of India', rate: 8.35 },
  { id: 'canara', name: 'Canara Bank', rate: 8.40 },
  { id: 'idbi', name: 'IDBI Bank', rate: 8.65 },
  { id: 'boi', name: 'Bank of India', rate: 8.40 },
  { id: 'indian', name: 'Indian Bank', rate: 8.40 },
  { id: 'yes', name: 'Yes Bank', rate: 9.00 },
  { id: 'indusind', name: 'IndusInd Bank', rate: 8.75 },
  { id: 'federal', name: 'Federal Bank', rate: 8.80 },
  { id: 'south-indian', name: 'South Indian Bank', rate: 8.70 },
  { id: 'bandhan', name: 'Bandhan Bank', rate: 9.15 },
  { id: 'uco', name: 'UCO Bank', rate: 8.45 },
  { id: 'iob', name: 'Indian Overseas Bank', rate: 8.40 },
  { id: 'central', name: 'Central Bank of India', rate: 8.45 },
];
